#!/bin/bash

CFLAGS+=( -march=core2 -msse4.1 )

CLANG=true
LTO=true
case "${PN}" in
    mpd|pycairo|libsecret|ncmpcpp|notmuch|paludis|libxkbui|TeXmacs|db)
    	CLANG=false
	;;&
    gdbm|pygtk|chmlib|libXfontcache|imlib2|libXxf86misc|db)
	LTO=fix
	;;&
    wv|ntfs-3g_ntfsprogs|dhcpcd|gmime|i3status|dwz|iputils|sysfsutils|file)
	LTO=hack
	;;&
    mpd|libsecret|ncmpcpp|djvu|paludis|openssh|cpio|bc|groff) # TODO: /usr/bin/x86_64-pc-linux-gnu-ld: error: ../lib/libbc.a: no archive symbol table (run ranlib)
	LTO=false
	;;&
    ### runtime breakage
    ### BIG FAT WARNING: dbus compiles with -flto, but breaks SYSTEMD at runtime!
    xapian-core|dbus|rxvt-unicode)
	LTO=false
	;;&
    xapian-core)
    	CLANG=false
	;;&
    *)
	;;
esac

### combination of compiler and lto
if [[ ${CLANG}x = truex ]]; then
    CC="clang"
    CXX="clang++"
    # clang-lto need special setting
    if [[ ${LTO}x != falsex ]]; then
	PATH="/etc/paludis/myconfig/scripts:${PATH}"
	AR="clang-ar"
	NM="nm --plugin /usr/lib64/LLVMgold.so"
	RANLIB=/bin/true
    fi
fi

if [[ ${LTO}x != falsex ]]; then
    CFLAGS+=( -flto )
    if [[ ${LTO} = fix ]]; then
	if [[ ${CLANG} = true ]]; then
	    LDFLAGS+=( -Wc,-flto ) # for clang (e.g. libXxf86misc)
	else
	    LDFLAGS+=( -Wl,-flto ) # for gcc (e.g. db)
	fi
    elif [[ ${LTO} = hack ]]; then
	CC+=" -flto"
	CXX+=" -flto"
    else
	LDFLAGS+=( -flto ) # for normal one
    fi
fi


### distcc
if is_in_2112; then
    PATH="/usr/libexec/distcc:${PATH}"
    DISTCC_DIR="/var/tmp/paludis/distcc"
    EXJOBS=10
    DISTCC_HOSTS='--randomize 10.2.112.2,lzo'
fi
#EMAKE_WRAPPER="pump"
#192.168.1.50,lzo,cpp


