* Package configuration specification

** set file
The package configuration set files are placed under
=${PALUDIS_CONFIG_DIR}/myconfig/packages=.

1. =@<machine-id>:<hostname>=

   A machine specific set which include machine related package
   configuration (mostly hardware), such as cpu features, video
   drivers, firmwares, etc.).

   The configurations in a machine set file will appear at the end of
   the paludis configurations, i.e., it has the highest priority and
   will overwrite other configurations.

2. =?<default>=

   A weak configuration set which only provides predefined package
   options or/and suggestions.

   It would not be added to the paludis installed world file. The
   configuration will be included in the front of the paludis
   configurations.

3. =<order>-<name>=

   Just an ordinary set with priority =<order>=.

** set file contents

1. Each line configurates a package.

2. Marks before any package spec at the start of a line will have
   special meanings:

   | =<TAB>=    | dependency        |
   | =+=        | repository unmask |
   | =~=        | unstable unmask   |
   | =-=        | user mask         |
   | =@requrie= | set inclusion     |
   | =@=        | build options     |

3. Any word after the leading package spec is the /options/
   configuration, with the exception of the package spec starting with
   =&= at the end of the line (see below).

4. A package spec starting with =&= at the end of the line will be
   included in the /suggestion/ configuration.

5. Each /build option/ configuration line must specify only one pair
   of a variable (e.g., CFLAGS, EXJOBS, CHOST, etc.) and its value,
   with the following marks supported:

   | =<no-mark>= | overwrite bashrc parameter   |
   | =^=         | insert into bashrc parameter |
   | =$=         | remove from bashrc parameter |

   Additionally, if the variable is "ALTERNATIVE", then the line
   configures the eclectic alternatives.

In the following example, the first line will unmask
=xorg-server-1.19.0-r1=, add it to a set, take the
=xf86-input-libinput= suggestion, configure its options as =systemd
xwayland providers: libressl -openssl=.

The second line will remove the =-ffast-math= CFLAGS and then insert a
=-O2= CFLAGS.

The third line just set EXJOBS to 1.

The last line tells paludis that glibc require ld.bfd to build.

#+BEGIN_EXAMPLE
+x11-server/xorg-server[=1.19.0-r1]		systemd xwayland providers: libressl -openssl		&xf86-input-libinput
@x11-server/xorg-server				CFLAGS: $-ffastmath ^-O2
@x11-server/xorg-server				EXJOBS: 1

@sys-libs/glibc					ALTERNATIVE: gcc 5.1
#+END_EXAMPLE
