#!/bin/bash

###### Paludis config ######
# platform
read -r -d '' PLATFORMS <<EOF
### defaults
*/*		amd64 ~amd64
*/*[=scm]	~amd64
EOF

# options
read -r -d '' OPTIONS <<EOF
*/*			-* pam systemd
*/*			threads openmp
*/*			acl xattr

*/*::x11		X

*/*			python_abis:		-* 2.7
*/*			build_options:		symbols=strip -recommended_tests
*/*			linguas:		zh_CN
EOF

# mirrors
SITES=( BJTU TSU USTC HEANET NETEASE BIR )
BJTU=(http://mirror.bjtu.edu.cn
    apache cpan cran 'ctan CTAN' debian freebsd 'gentoo gentoo/distfiles' gimp gnome gnu kde 'kernel kernel/pub' 'libreoffice tdf/libreoffice')
TSU=( http://mirrors.tuna.tsinghua.edu.cn
    apache 'ctan CTAN' 'cran CRAN' 'ctan CTAN' debian freebsd 'gentoo gentoo/distfiles' gnu 'kernel kernel/pub' opensuse )
USTC=( http://mirrors.ustc.edu.cn
    'cpan CPAN' 'cran CRAN' 'ctan CTAN' debian freebsd 'gentoo gentoo/distfiles' gnome gnu kde 'kernel linux-kernel' opensuse )
HEANET=( http://heanet.dl.sourceforge.net sourceforge )
NETEASE=( http://mirrors.163.com
    cpan debian 'freebsd FreeBSD' 'gentoo gentoo/distfiles' 'opensuse openSUSE')
BIR=( http://10.2.112.3 subi-bin )
#### Paludis config end ####

###### Script config ######
CONFIG_DIR=$(dirname ${SCRIPT_DIR})
ACTION=$(basename ${0%.bash})
HOST=`hostname|cut -d. -f1`

SETS=()
for s in cui gui; do
    [[ -f ${CONFIG_DIR}/${s} ]] && SETS+=( "${s} ${CONFIG_DIR}/${s}" )
done
[[ -f ${CONFIG_DIR}/packages.${HOST} ]] && SETS+=( "host ${CONFIG_DIR}/packages.${HOST}" )

eval WORLD=`${CONFIG_DIR}/../general.bash | grep world | cut -d' ' -f3`
WORLD=( `cat ${WORLD}` )
#### Script config end ####

