#!/bin/bash

SCRIPT_DIR=$(dirname `readlink -f $0`)
source ${SCRIPT_DIR}/config

remove_comment_and_platform() {
    sed -r -e '/#.*/d' -e 's/~//' -e '/^[[:blank:]]*$/d'
}
remove_custom_mark() {
    sed -e 's/+.*//' -e 's/&.*//'
}

####### Actions #######
show_platforms() {
    echo "${PLATFORMS}"
}

show_set() {
    s=$1
    set -- ${SETS[@]}
    while [[ $# -gt 0 ]]; do
	if [[ $1 == $s ]]; then
	    cat $2 | remove_comment_and_platform | awk '!/^[[:blank:]*]/ {print "* " $1}'
	    break
	fi
	shift
	shift
    done
}

show_cui() {
    show_set cui
}

show_gui() {
    show_set gui
}

show_host() {
    show_set host
}

show_options() {
    echo "${OPTIONS}"
    set -- ${SETS[@]}
    while [[ $# -gt 0 ]]; do
	for w in ${WORLD[@]}; do
	    if [[ $1 == $w ]]; then
		cat ${2} | remove_comment_and_platform | remove_custom_mark | awk '{if (NF>1) print}'
	    fi
	done
	shift
	shift
    done
}

show_suggestions() {
    set -- ${SETS[@]}
    while [[ $# -gt 0 ]]; do
	shift
	cat $1 | remove_comment_and_platform | sed -r -n '/&/ s/[[:blank:]]*([[:punct:][:alnum:]]+).*&/\1\t/ p'
	shift
    done
}

show_package_unmask() {
    set -- ${SETS[@]}
    while [[ $# -gt 0 ]]; do
	shift
	cat $1 | remove_comment_and_platform | sed -r -n '/\+/ s/[[:blank:]]*([[:punct:][:alnum:]]+).*\+/\1/ p'
	shift
    done
}

show_mirrors() {
    add_mirror()
    {
	url_base=$1
	set -- $2
    
	url="$url_base/${2:-$1}"
	name=$1

	num=${#MIRRORS[@]}
	for ((i=0; i<$num; i++)); do
	    set -- ${MIRRORS[i]}
	    if [[ $name == $1 ]]; then
		MIRRORS[i]+=" $url"
		return 0
	    fi
	done
	MIRRORS+=( "$name $url" )
	return 0
    }

    MIRRORS=()
    for site in ${SITES[@]}; do
	eval site=\( \${${site}[@]} \)
	set -- ${site[@]}
	url_base=$1; shift
	while [[ $# -gt 0 ]]; do
	    add_mirror "$url_base" "$1"
	    shift
	done
    done

    for m in "${MIRRORS[@]}"; do
	echo ${m}
    done
}

if [[ -d ${CONFIG_DIR} ]]; then
    case "$ACTION" in
	*)
            show_${ACTION}
	    ;;
    esac
else
    echo "The config dir does not exist."
fi
